version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./kaizntree-service-infra
    volumes:
      - ./kaizntree-service-infra:/app
    env_file:
      - ./kaizntree-service-infra/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./kaizntree-web-app
    volumes:
      - ./kaizntree-web-app:/app
    env_file:
      - ./kaizntree-web-app/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
